### ISSUE TITLE
Difference in outAmount in API and jup.ag

### ISSUE THREAD

**Issue by placzkowski** [jup-ag/jupiter-quote-api-node#1]
For last few hours I get wrong outAmount when accessing https://quote-api.jup.ag/v1/quote
For example: https://quote-api.jup.ag/v1/quote?inputMint=FCqfQSujuPxy6V42UvafBhsysWtEq1vhjfMN1PUbgaxA&outputMint=F6v4wfAdJB8D8p77bMXZgYt8TDKsYxLYxH5AFhUkYx9W&amount=1400000000000
Gives outAmount: 251950000
Amount on Jupiter website: 24,38
I think that Mercurial prices are not updating in API but I'm not sure.

**Comment by ZhengYuTay** [comment]
> For last few hours I get wrong outAmount when accessing [quote-api.jup.ag/v1/quote](https://quote-api.jup.ag/v1/quote) For example: [quote-api.jup.ag/v1/quote?inputMint=FCqfQSujuPxy6V42UvafBhsysWtEq1vhjfMN1PUbgaxA&outputMint=F6v4wfAdJB8D8p77bMXZgYt8TDKsYxLYxH5AFhUkYx9W&amount=1400000000000](https://quote-api.jup.ag/v1/quote?inputMint=FCqfQSujuPxy6V42UvafBhsysWtEq1vhjfMN1PUbgaxA&outputMint=F6v4wfAdJB8D8p77bMXZgYt8TDKsYxLYxH5AFhUkYx9W&amount=1400000000000) Gives outAmount: 251950000 Amount on Jupiter website: 24,38 I think that Mercurial prices are not updating in API but I'm not sure.

This should be fixed now
